// Code generated by MockGen. DO NOT EDIT.
// Source: metricsManager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncHTTPRequests mocks base method.
func (m *MockMetrics) IncHTTPRequests(method, endpoint, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncHTTPRequests", method, endpoint, status)
}

// IncHTTPRequests indicates an expected call of IncHTTPRequests.
func (mr *MockMetricsMockRecorder) IncHTTPRequests(method, endpoint, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncHTTPRequests", reflect.TypeOf((*MockMetrics)(nil).IncHTTPRequests), method, endpoint, status)
}

// IncPVZCreated mocks base method.
func (m *MockMetrics) IncPVZCreated() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncPVZCreated")
}

// IncPVZCreated indicates an expected call of IncPVZCreated.
func (mr *MockMetricsMockRecorder) IncPVZCreated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncPVZCreated", reflect.TypeOf((*MockMetrics)(nil).IncPVZCreated))
}

// IncProductsCreated mocks base method.
func (m *MockMetrics) IncProductsCreated() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncProductsCreated")
}

// IncProductsCreated indicates an expected call of IncProductsCreated.
func (mr *MockMetricsMockRecorder) IncProductsCreated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncProductsCreated", reflect.TypeOf((*MockMetrics)(nil).IncProductsCreated))
}

// IncReceptionsCreated mocks base method.
func (m *MockMetrics) IncReceptionsCreated() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncReceptionsCreated")
}

// IncReceptionsCreated indicates an expected call of IncReceptionsCreated.
func (mr *MockMetricsMockRecorder) IncReceptionsCreated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncReceptionsCreated", reflect.TypeOf((*MockMetrics)(nil).IncReceptionsCreated))
}

// ObserveHTTPRequestDuration mocks base method.
func (m *MockMetrics) ObserveHTTPRequestDuration(method, endpoint string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveHTTPRequestDuration", method, endpoint, duration)
}

// ObserveHTTPRequestDuration indicates an expected call of ObserveHTTPRequestDuration.
func (mr *MockMetricsMockRecorder) ObserveHTTPRequestDuration(method, endpoint, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveHTTPRequestDuration", reflect.TypeOf((*MockMetrics)(nil).ObserveHTTPRequestDuration), method, endpoint, duration)
}
