// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "avito/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockStorage) AddProduct(ctx context.Context, product models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockStorageMockRecorder) AddProduct(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockStorage)(nil).AddProduct), ctx, product)
}

// CheckUser mocks base method.
func (m *MockStorage) CheckUser(ctx context.Context, email string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUser", ctx, email)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUser indicates an expected call of CheckUser.
func (mr *MockStorageMockRecorder) CheckUser(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUser", reflect.TypeOf((*MockStorage)(nil).CheckUser), ctx, email)
}

// CreatePvz mocks base method.
func (m *MockStorage) CreatePvz(ctx context.Context, pvz models.PVZ) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePvz", ctx, pvz)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePvz indicates an expected call of CreatePvz.
func (mr *MockStorageMockRecorder) CreatePvz(ctx, pvz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePvz", reflect.TypeOf((*MockStorage)(nil).CreatePvz), ctx, pvz)
}

// CreateReception mocks base method.
func (m *MockStorage) CreateReception(ctx context.Context, reception models.Reception) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReception", ctx, reception)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReception indicates an expected call of CreateReception.
func (mr *MockStorageMockRecorder) CreateReception(ctx, reception interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReception", reflect.TypeOf((*MockStorage)(nil).CreateReception), ctx, reception)
}

// CreateUser mocks base method.
func (m *MockStorage) CreateUser(ctx context.Context, user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorageMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorage)(nil).CreateUser), ctx, user)
}

// DeleteProduct mocks base method.
func (m *MockStorage) DeleteProduct(ctx context.Context, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockStorageMockRecorder) DeleteProduct(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockStorage)(nil).DeleteProduct), ctx, productID)
}

// GetLastProductByReception mocks base method.
func (m *MockStorage) GetLastProductByReception(ctx context.Context, receptionID uuid.UUID) (models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastProductByReception", ctx, receptionID)
	ret0, _ := ret[0].(models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastProductByReception indicates an expected call of GetLastProductByReception.
func (mr *MockStorageMockRecorder) GetLastProductByReception(ctx, receptionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastProductByReception", reflect.TypeOf((*MockStorage)(nil).GetLastProductByReception), ctx, receptionID)
}

// GetLastReceptionInProgress mocks base method.
func (m *MockStorage) GetLastReceptionInProgress(ctx context.Context, pvzId uuid.UUID) (models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReceptionInProgress", ctx, pvzId)
	ret0, _ := ret[0].(models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReceptionInProgress indicates an expected call of GetLastReceptionInProgress.
func (mr *MockStorageMockRecorder) GetLastReceptionInProgress(ctx, pvzId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReceptionInProgress", reflect.TypeOf((*MockStorage)(nil).GetLastReceptionInProgress), ctx, pvzId)
}

// GetPVZByID mocks base method.
func (m *MockStorage) GetPVZByID(ctx context.Context, id uuid.UUID) (models.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPVZByID", ctx, id)
	ret0, _ := ret[0].(models.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPVZByID indicates an expected call of GetPVZByID.
func (mr *MockStorageMockRecorder) GetPVZByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPVZByID", reflect.TypeOf((*MockStorage)(nil).GetPVZByID), ctx, id)
}

// GetPVZReceptions mocks base method.
func (m *MockStorage) GetPVZReceptions(ctx context.Context, pvzId uuid.UUID, startDate, endDate *time.Time) ([]models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPVZReceptions", ctx, pvzId, startDate, endDate)
	ret0, _ := ret[0].([]models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPVZReceptions indicates an expected call of GetPVZReceptions.
func (mr *MockStorageMockRecorder) GetPVZReceptions(ctx, pvzId, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPVZReceptions", reflect.TypeOf((*MockStorage)(nil).GetPVZReceptions), ctx, pvzId, startDate, endDate)
}

// GetPvzList mocks base method.
func (m *MockStorage) GetPvzList(ctx context.Context, pvzList models.PvzListRequest) ([]models.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPvzList", ctx, pvzList)
	ret0, _ := ret[0].([]models.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPvzList indicates an expected call of GetPvzList.
func (mr *MockStorageMockRecorder) GetPvzList(ctx, pvzList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPvzList", reflect.TypeOf((*MockStorage)(nil).GetPvzList), ctx, pvzList)
}

// GetReceptionProducts mocks base method.
func (m *MockStorage) GetReceptionProducts(ctx context.Context, receptionId uuid.UUID) ([]models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceptionProducts", ctx, receptionId)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceptionProducts indicates an expected call of GetReceptionProducts.
func (mr *MockStorageMockRecorder) GetReceptionProducts(ctx, receptionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceptionProducts", reflect.TypeOf((*MockStorage)(nil).GetReceptionProducts), ctx, receptionId)
}

// UpdateReceptionStatus mocks base method.
func (m *MockStorage) UpdateReceptionStatus(ctx context.Context, receptionID uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReceptionStatus", ctx, receptionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReceptionStatus indicates an expected call of UpdateReceptionStatus.
func (mr *MockStorageMockRecorder) UpdateReceptionStatus(ctx, receptionID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReceptionStatus", reflect.TypeOf((*MockStorage)(nil).UpdateReceptionStatus), ctx, receptionID, status)
}
